<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_org.openqa.selenium</name>
   <tag></tag>
   <elementGuidId>4e8bfe65-f3cb-45a9-a4bf-c5ef5ddb07b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'org.openqa.selenium')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9658ef76-fc8e-45f0-8aa3-54c918d23b9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>org/openqa/selenium/package-frame.html</value>
      <webElementGuid>ed387c01-04eb-42b3-aa16-7102bab495ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>packageFrame</value>
      <webElementGuid>0a344255-1f69-4722-b96c-c81407433257</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>org.openqa.selenium</value>
      <webElementGuid>7adc1f3d-4733-4012-85d3-78b6801f0896</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;indexContainer&quot;]/ul[1]/li[1]/a[1]</value>
      <webElementGuid>fc650c7e-ed79-43c7-b105-f9d78651a1e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_selenium-api 3.141.59 javadoc (org.sel_3b98a0/frame_html1frameset1frameset1frame1_package_d3e5c8</value>
      <webElementGuid>69e542d4-a00e-4d69-9c5f-c8bf99cbd582</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'org.openqa.selenium')]</value>
      <webElementGuid>20b15e3c-eefc-4d65-8493-1deb5c7d4a9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Packages'])[1]/following::a[1]</value>
      <webElementGuid>4128cd03-44c3-4933-956d-dbdfb4aa0d81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Classes'])[1]/following::a[1]</value>
      <webElementGuid>dfabb82b-cd41-4002-a39f-708ba27a381a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='org.openqa.selenium.html5'])[1]/preceding::a[1]</value>
      <webElementGuid>04978224-4cec-4cc9-80eb-e2e33302e28c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='org.openqa.selenium.interactions'])[1]/preceding::a[2]</value>
      <webElementGuid>78265f83-a4d4-4729-a247-dd7a040f1f8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='org.openqa.selenium']/parent::*</value>
      <webElementGuid>0c34e781-b3e9-41dd-85b9-b74f17fd5798</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'org/openqa/selenium/package-frame.html')]</value>
      <webElementGuid>8861254e-8160-4b2f-9c54-e16e60b2bd84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a</value>
      <webElementGuid>cd78a730-0cb8-4c67-98aa-aefda0088cf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'org/openqa/selenium/package-frame.html' and (text() = 'org.openqa.selenium' or . = 'org.openqa.selenium')]</value>
      <webElementGuid>3d535ffb-e43a-43a3-8b5d-9dde6379361b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
