<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_false_promptexample</name>
   <tag></tag>
   <elementGuidId>575cb8a0-1b57-4f47-be8f-cb6e9da6c8e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#promptexample</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='promptexample']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8354ddbf-950a-4899-bf48-d3c0740bff70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styled-click-button</value>
      <webElementGuid>b73b3cff-8922-4916-8ab7-52bc579d56ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>promptexample</value>
      <webElementGuid>a041244e-e532-4d8e-8b15-8d1605bcd6a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2385a9bd-66ba-4a18-8fbc-8e1d3ac599bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>show_prompt()</value>
      <webElementGuid>dfd30d93-81a2-46c8-b619-909f65f8e7a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Show prompt box</value>
      <webElementGuid>0b5d210a-b638-4d9d-879c-d68d01620b68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;promptexample&quot;)</value>
      <webElementGuid>e22889e4-48ba-4348-a926-b0781440c594</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='promptexample']</value>
      <webElementGuid>ba73a5f6-593d-4830-b3cb-46affc45a624</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/input</value>
      <webElementGuid>287ab4e8-ac36-4167-9202-0232a8955965</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'promptexample' and @type = 'button']</value>
      <webElementGuid>b2c418cd-3b1b-4328-afb2-5a14b4e99cc7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
