<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Videos</name>
   <tag></tag>
   <elementGuidId>3e32e5fc-0534-4da2-b149-643c3f84c456</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='hdtb-msb']/div/div/div[4]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f41b9502-5bb6-4a51-a1c8-33fbc4e01df3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/search?q=Automation+Testing&amp;source=lnms&amp;tbm=vid&amp;sa=X&amp;ved=2ahUKEwjc773uy6T3AhWVmXIEHRVbC_AQ_AUoA3oECAEQBQ</value>
      <webElementGuid>21c2ed2b-bf43-426d-a5ca-4af2fc29a680</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hveid</name>
      <type>Main</type>
      <value>CAEQBQ</value>
      <webElementGuid>7dc514a2-ce36-4fae-a8e1-23aaa48f10d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Videos</value>
      <webElementGuid>4f6be28f-df93-4669-a243-85bcc306da32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hdtb-msb&quot;)/div[1]/div[@class=&quot;MUFPAc&quot;]/div[@class=&quot;hdtb-mitem&quot;]/a[1]</value>
      <webElementGuid>c6e3c774-1764-4a7a-8224-3f4f052eae38</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hdtb-msb']/div/div/div[4]/a</value>
      <webElementGuid>9b7dce23-7b44-4776-8efc-c6c217173ae7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Videos')]</value>
      <webElementGuid>17537bdd-6714-4e06-9d5d-3128c3148ed4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Images'])[1]/following::a[1]</value>
      <webElementGuid>4ee650fd-e1a9-4373-8169-3abb94029e84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Books'])[1]/following::a[2]</value>
      <webElementGuid>35fe6dd6-256a-4cac-8d30-34842502b783</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='News'])[1]/preceding::a[1]</value>
      <webElementGuid>13d1e596-e6fd-4d61-99d5-d1652ae502c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='More'])[1]/preceding::a[2]</value>
      <webElementGuid>896e0a20-fb02-4ba4-a785-a9cb0642e3eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Videos']/parent::*</value>
      <webElementGuid>dd159367-fd76-4f5e-bcb3-d2babb584f5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/search?q=Automation+Testing&amp;source=lnms&amp;tbm=vid&amp;sa=X&amp;ved=2ahUKEwjc773uy6T3AhWVmXIEHRVbC_AQ_AUoA3oECAEQBQ')]</value>
      <webElementGuid>8a154ca9-ee08-4b79-83d4-7ab2ae839ca4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/a</value>
      <webElementGuid>d7ffd373-f3d4-4236-8638-9fc19eab2057</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/search?q=Automation+Testing&amp;source=lnms&amp;tbm=vid&amp;sa=X&amp;ved=2ahUKEwjc773uy6T3AhWVmXIEHRVbC_AQ_AUoA3oECAEQBQ' and (text() = 'Videos' or . = 'Videos')]</value>
      <webElementGuid>545fc164-4291-4d48-8a95-dc0e91d0004b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
