<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Alert Box Examples_alertexamples</name>
   <tag></tag>
   <elementGuidId>43a60673-378e-4411-9ecd-a0f1ebb25111</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='alertexamples']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#alertexamples</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e2cb2f3b-3876-40c4-babf-e4f748dc9fba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styled-click-button</value>
      <webElementGuid>705b71ab-6b4f-43f9-89c9-08660177065b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>alertexamples</value>
      <webElementGuid>3f757998-31bc-43c7-a643-094f1342b954</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>408541c6-bad6-4df8-bb98-197f8b4bb7f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>show_alert()</value>
      <webElementGuid>2746d9f3-77c0-4e17-81dc-7936fcfea5d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Show alert box</value>
      <webElementGuid>54d5f853-eab2-46c1-a663-8d3edb24cc18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;alertexamples&quot;)</value>
      <webElementGuid>a30f51a5-f2f3-4391-8536-c89c1e0c3961</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='alertexamples']</value>
      <webElementGuid>90415a85-d095-4573-bb92-d73c897f8280</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>9b267412-184d-4e41-8685-d02737fe912f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'alertexamples' and @type = 'button']</value>
      <webElementGuid>0e38aecd-9306-46c5-8c96-5fb657d661a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
